# Nginx для балансировки http трафика
---
- hosts: cloud
  become: true
  roles:
  - geerlingguy.nginx
  vars_files:
    - "vars.yaml"
  tasks:
  - name: "Enable EPEL repo"
    ansible.builtin.yum:
      name: "epel-release"
      state: "present"
      update_cache: false
  - name: "Install snapd"
    ansible.builtin.yum:
      name: "snapd"
      state: "present"
      update_cache: true
  - name: "Start service snapd"
    ansible.builtin.service:
      name: "snapd"
      state: "started"
      enabled: true
  - name: "Installing core for snapd"
    community.general.snap:
      name: "core"
  - name: "Create a symbolic link for snapd"
    ansible.builtin.file:
      src: "/var/lib/snapd/snap"
      dest: "/snap"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: "link"
  - name: "Install certbot"
    community.general.snap:
      name: "certbot"
      classic: true
  - name: "Create a symbolic link for certbot"
    ansible.builtin.file:
      src: "/snap/bin/certbot"
      dest: "/usr/bin/certbot"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: "link"
...