---
- hosts: cloud
  become: true
  roles:
  - geerlingguy.nginx
  - certbot
  vars_files:
    - "vars.yaml"
  pre_tasks:
  - name: "Enable EPEL repo"
    ansible.builtin.yum:
      name: "epel-release"
      state: "present"
      update_cache: false
  - name: "Installing Python 3"
    ansible.builtin.yum:
      name: "python3"
      state: "present"
      update_cache: true
...